spring.application.name=school-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/school_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# JWT CONFIGURATION
# ===============================
jwt.secret=mySecretKey123
jwt.expiration=3600000

file.upload-dir=D:/CLI Work/School_ERP/school-management-system/uploads/
